from keyboards.default.user.bar_menu import *
from keyboards.default.user.beer_in_can import *
from keyboards.default.user.beer_in_can import *
from keyboards.default.user.football_broadcasts import *
from keyboards.default.user.loyalty_program import *
from keyboards.default.user.main_menu import *
from keyboards.default.user.our_establishments import *
from keyboards.default.user.reserve_table import *
from keyboards.default.user.review import *
from keyboards.default.user.startKB import *
